#!/bin/bash
#
# Copyright 2019 Telefonica Investigación y Desarrollo, S.A.U
#
# This file is part of iotagent-json
#
# iotagent-json is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# iotagent-json is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with iotagent-json. If not, see http://www.gnu.org/licenses/.
#
# For those usages not covered by the GNU Affero General Public License please contact
# with iot_support at tid dot es

# How this hook thing works? :) It a way of telling dockerhub autobuild how
# to build the container. It is explained at https://docs.docker.com/docker-hub/builds/advanced,
# including the different env var (such as IMAGE_NAME, etc.) that can be used here. An
# easy to understand example can be found here: https://dev.to/samuelea/automate-your-builds-on-docker-hub-by-writing-a-build-hook-script-13fp
#
# Not every repository needs hooks, only the ones that needs special tunning. Standard
# dockerhub autobuild works well most of the times.

docker image push $IMAGE_NAME-pm2 

#docker image push $IMAGE_NAME-distroless


